source 'https://rubygems.org'
gem 'rails', '4.2.5'
gem 'rails-api'
gem 'omniauth', '~> 1.3', '>= 1.3.1'
gem 'devise_token_auth'
gem 'spring', :group => :development
gem 'pg'
gem 'bcrypt'
gem 'rb-readline'
gem 'stripe', '>= 1.27.0'
gem 'newrelic_rpm'
gem 'rack-cors', require: 'rack/cors'
gem 'active_model_serializers', github: 'rails-api/active_model_serializers'
gem 'nokogiri'
gem 'slugify'
gem 'mailgun_rails'
gem 'thin'
group :development, :test do
  gem 'database_cleaner'
  gem 'faker'
  gem 'rspec-rails', '~> 3.0'
  gem 'factory_girl_rails', '~> 4.0'
  gem 'stripe-ruby-mock', :require => 'stripe_mock'
end
